#!/bin/bash
#
# Bootstrap script for rasppi-utils
# Sets up a Raspberry Pi with Supabase keep-alive and other utilities
#
# Usage: sudo ./bootstrap.sh
#
# This script is idempotent - safe to run multiple times.

set -e

# Configuration
INSTALL_DIR="/opt/rasppi-utils"
CONFIG_DIR="/etc/rasppi-utils"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

# Install system dependencies
install_system_deps() {
    log_info "Installing system dependencies..."
    apt-get update
    apt-get install -y python3 python3-pip python3-venv
    log_info "System dependencies installed"
}

# Copy project files to install directory
install_project_files() {
    log_info "Installing project files to ${INSTALL_DIR}..."

    # Create install directory if it doesn't exist
    mkdir -p "${INSTALL_DIR}"

    # Copy project files (excluding .git, .venv, tests, etc.)
    rsync -a --delete \
        --exclude='.git' \
        --exclude='.venv' \
        --exclude='__pycache__' \
        --exclude='.pytest_cache' \
        --exclude='tests' \
        --exclude='.claude' \
        --exclude='designs' \
        "${SCRIPT_DIR}/" "${INSTALL_DIR}/"

    log_info "Project files installed"
}

# Create virtual environment and install Python dependencies
setup_venv() {
    log_info "Setting up Python virtual environment..."

    # Create venv if it doesn't exist
    if [[ ! -d "${INSTALL_DIR}/.venv" ]]; then
        python3 -m venv "${INSTALL_DIR}/.venv"
        log_info "Virtual environment created"
    else
        log_info "Virtual environment already exists"
    fi

    # Install/upgrade dependencies
    "${INSTALL_DIR}/.venv/bin/pip" install --upgrade pip
    "${INSTALL_DIR}/.venv/bin/pip" install -r "${INSTALL_DIR}/requirements.txt"

    log_info "Python dependencies installed"
}

# Prompt for Supabase credentials and write config
setup_config() {
    log_info "Setting up configuration..."

    # Create config directory
    mkdir -p "${CONFIG_DIR}"

    # Check if config already exists
    if [[ -f "${CONFIG_DIR}/.env" ]]; then
        log_warn "Configuration file already exists at ${CONFIG_DIR}/.env"
        read -p "Do you want to reconfigure? (y/N): " reconfigure
        if [[ ! "${reconfigure}" =~ ^[Yy]$ ]]; then
            log_info "Keeping existing configuration"
            return
        fi
    fi

    echo ""
    echo "Please enter your Supabase credentials."
    echo "You can find these at: https://app.supabase.com/project/_/settings/api"
    echo ""

    read -p "Supabase URL (e.g., https://xxxxx.supabase.co): " supabase_url
    read -p "Supabase API Key (anon/public key): " supabase_key

    # Validate inputs
    if [[ -z "${supabase_url}" ]] || [[ -z "${supabase_key}" ]]; then
        log_error "Both URL and API key are required"
        exit 1
    fi

    # Write config file
    cat > "${CONFIG_DIR}/.env" << EOF
# Supabase credentials
# Generated by bootstrap.sh on $(date)
SUPABASE_URL=${supabase_url}
SUPABASE_KEY=${supabase_key}
EOF

    # Secure the config file
    chmod 600 "${CONFIG_DIR}/.env"

    log_info "Configuration saved to ${CONFIG_DIR}/.env"
}

# Install systemd unit files
install_systemd_units() {
    log_info "Installing systemd unit files..."

    # Copy service and timer files
    cp "${INSTALL_DIR}/systemd/supabase-keepalive.service" /etc/systemd/system/
    cp "${INSTALL_DIR}/systemd/supabase-keepalive.timer" /etc/systemd/system/

    # Reload systemd to pick up new units
    systemctl daemon-reload

    log_info "Systemd unit files installed"
}

# Enable and start the timer
enable_timer() {
    log_info "Enabling and starting supabase-keepalive timer..."

    # Enable timer to start on boot
    systemctl enable supabase-keepalive.timer

    # Start timer now
    systemctl start supabase-keepalive.timer

    log_info "Timer enabled and started"

    # Show timer status
    echo ""
    log_info "Timer status:"
    systemctl status supabase-keepalive.timer --no-pager || true
}

# Run a test to verify the setup
verify_setup() {
    log_info "Verifying setup..."

    # Run the keep-alive script once to test
    if "${INSTALL_DIR}/.venv/bin/python" "${INSTALL_DIR}/scripts/supabase_keepalive.py"; then
        log_info "Verification successful - Supabase keep-alive is working!"
    else
        log_warn "Verification failed - please check your credentials"
        log_warn "You can reconfigure by running: sudo ${INSTALL_DIR}/bootstrap.sh"
    fi
}

# Main function
main() {
    echo ""
    echo "=========================================="
    echo "  rasppi-utils Bootstrap Script"
    echo "=========================================="
    echo ""

    check_root
    install_system_deps
    install_project_files
    setup_venv
    setup_config
    install_systemd_units
    enable_timer
    verify_setup

    echo ""
    echo "=========================================="
    log_info "Bootstrap complete!"
    echo "=========================================="
    echo ""
    echo "The Supabase keep-alive timer is now running daily."
    echo "To check status: systemctl status supabase-keepalive.timer"
    echo "To view logs: journalctl -u supabase-keepalive.service"
    echo ""
}

main "$@"
